### ISSUE TITLE
[Bug] Game crashes when saving

### ISSUE THREAD

**Issue by kasimirmoilanen** [WelehoBRUDER/Dungeons-of-Tavaraen#3] opened 2022-02-10 11:56 UTC
```
Uncaught TypeError: can't convert undefined to object
    getModifiers https://welehobruder.github.io/Dungeons-of-Tavaraen/resources/compiledJS/script/character.js line 20 > srcScript:280
    getModifiers https://welehobruder.github.io/Dungeons-of-Tavaraen/resources/compiledJS/script/character.js line 20 > srcScript:279
    sight https://welehobruder.github.io/Dungeons-of-Tavaraen/resources/compiledJS/script/player.js line 20 > srcScript:101
    renderMap https://welehobruder.github.io/Dungeons-of-Tavaraen/resources/compiledJS/script/map.js line 20 > srcScript:111
    modifyCanvas https://welehobruder.github.io/Dungeons-of-Tavaraen/resources/compiledJS/script/map.js line 20 > srcScript:1125
character.ts:322:11
    getModifiers character.ts:322
    forEach self-hosted:208
    getModifiers character.ts:321
    sight player.ts:199
    renderMap map.ts:131
    modifyCanvas map.ts:1057
```

**Comment by kasimirmoilanen** [comment] 2022-02-10 12:01
```
Uncaught TypeError: can't convert undefined to object
    getModifiers https://welehobruder.github.io/Dungeons-of-Tavaraen/resources/compiledJS/script/character.js line 20 > srcScript:280
    getModifiers https://welehobruder.github.io/Dungeons-of-Tavaraen/resources/compiledJS/script/character.js line 20 > srcScript:279
    sight https://welehobruder.github.io/Dungeons-of-Tavaraen/resources/compiledJS/script/player.js line 20 > srcScript:101
    renderMap https://welehobruder.github.io/Dungeons-of-Tavaraen/resources/compiledJS/script/map.js line 20 > srcScript:111
    modifyCanvas https://welehobruder.github.io/Dungeons-of-Tavaraen/resources/compiledJS/script/map.js line 20 > srcScript:1125
character.ts:322:11
    getModifiers character.ts:322
    forEach self-hosted:208
    getModifiers character.ts:321
    sight player.ts:199
    renderMap map.ts:131
    modifyCanvas map.ts:1057
```

**Comment by WelehoBRUDER** [comment] 2022-02-11 19:55
This issue is fixed in a yet unreleased update, it was caused by the game altering the player object to trim down save file size, but not restoring the player to a playable state.

**Closed by WelehoBRUDER** 2022-02-11 19:55 UTC
Labels: bug
